import { Option, IConstructor } from "@aicacia/core";
import { Plugin } from "../../sceneGraph";
import { InputAxis } from "./InputAxis";
import { InputButton } from "./InputButton";
import { InputHandler } from "./InputHandler";
export declare class Input extends Plugin {
    static pluginPriority: number;
    private element;
    private inputHandlers;
    private inputHandlerMap;
    private buttons;
    private axes;
    constructor(element: Element);
    getElement(): Element;
    addAxes(...axes: InputAxis[]): this;
    addAxis(...axes: InputAxis[]): this;
    getAxis(name: string): Option<InputAxis>;
    getAxisValue(name: string): Option<number>;
    getRequiredAxis(name: string): InputAxis;
    getRequiredAxisValue(name: string): number;
    getInputHandler<I extends InputHandler = InputHandler>(InputHandler: IConstructor<I>): Option<InputHandler<Input>>;
    getRequiredInputHandler<I extends InputHandler = InputHandler>(InputHandler: IConstructor<I>): InputHandler<Input>;
    removeAxes(...axes: InputAxis[]): this;
    removeAxis(...axes: InputAxis[]): this;
    addInputHandlers(...inputHandlers: InputHandler[]): this;
    addInputHandler(...inputHandlers: InputHandler[]): this;
    removeInputHandlers(...inputHandlers: IConstructor<InputHandler>[]): this;
    removeInputHandler(...inputHandlers: IConstructor<InputHandler>[]): this;
    getOrCreateButton(name: string): InputButton;
    getButton(name: string): Option<InputButton>;
    getValue(name: string): number;
    isDown(name: string): boolean;
    isUp(name: string): boolean;
    onUpdate(): this;
    onAfterUpdate(): this;
    private _addAxis;
    private _removeAxis;
    private updateAxes;
    private updateAxis;
    private _addInputHandler;
    private _removeInputHandler;
}
