import { Option, IConstructor } from "@aicacia/core";
import { Plugin } from "../../Plugin";
import { InputAxis } from "./InputAxis";
import { InputButton } from "./InputButton";
import { InputHandler } from "./InputHandler";
import { EventListener } from "./EventListener";
import { InputEvent } from "./InputEvent";
export declare class Input extends Plugin {
    private events;
    private inputHandlers;
    private inputHandlerMap;
    private eventListeners;
    private eventListenerMap;
    private buttons;
    private axes;
    constructor();
    queueEvent(event: InputEvent): this;
    addAxes(...axes: InputAxis[]): this;
    addAxis(...axes: InputAxis[]): this;
    getAxis(name: string): Option<InputAxis>;
    getAxisValue(name: string): Option<number>;
    getRequiredAxis(name: string): InputAxis;
    getRequiredAxisValue(name: string): number;
    getInputHandler<I extends InputHandler = InputHandler>(InputHandler: IConstructor<I>): Option<InputHandler<Input>>;
    getRequiredInputHandler<I extends InputHandler = InputHandler>(InputHandler: IConstructor<I>): InputHandler<Input>;
    getEventListener<I extends EventListener = EventListener>(EventListener: IConstructor<I>): Option<EventListener<Input>>;
    getRequiredEventListener<I extends EventListener = EventListener>(EventListener: IConstructor<I>): EventListener<Input>;
    removeAxes(...axes: InputAxis[]): this;
    removeAxis(...axes: InputAxis[]): this;
    addInputHandlers(...inputHandlers: InputHandler[]): this;
    addInputHandler(...inputHandlers: InputHandler[]): this;
    removeInputHandlers(...inputHandlers: IConstructor<InputHandler>[]): this;
    removeInputHandler(...inputHandlers: IConstructor<InputHandler>[]): this;
    addEventListeners(...eventListeners: EventListener[]): this;
    addEventListener(...eventListeners: EventListener[]): this;
    removeEventListeners(...eventListeners: IConstructor<EventListener>[]): this;
    removeEventListener(...eventListeners: IConstructor<EventListener>[]): this;
    getOrCreateButton(name: string): InputButton;
    getButton(name: string): Option<InputButton>;
    getValue(name: string): number;
    isDown(name: string): boolean;
    isUp(name: string): boolean;
    onUpdate(): this;
    onAfterUpdate(): this;
    private _addAxis;
    private _removeAxis;
    private updateAxes;
    private updateAxis;
    private _addInputHandler;
    private _removeInputHandler;
    private _addEventListener;
    private _removeEventListener;
}
