"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var getGlobalCanvas_1 = require("./getGlobalCanvas");
Object.defineProperty(exports, "getGlobalCanvas", { enumerable: true, get: function () { return getGlobalCanvas_1.getGlobalCanvas; } });
var getGlobalContext_1 = require("./getGlobalContext");
Object.defineProperty(exports, "getGlobalContext", { enumerable: true, get: function () { return getGlobalContext_1.getGlobalContext; } });
var getTextDimensions_1 = require("./getTextDimensions");
Object.defineProperty(exports, "getTextHeight", { enumerable: true, get: function () { return getTextDimensions_1.getTextHeight; } });
Object.defineProperty(exports, "getTextUnitHeight", { enumerable: true, get: function () { return getTextDimensions_1.getTextUnitHeight; } });
Object.defineProperty(exports, "getTextUnitWidth", { enumerable: true, get: function () { return getTextDimensions_1.getTextUnitWidth; } });
Object.defineProperty(exports, "getTextWidth", { enumerable: true, get: function () { return getTextDimensions_1.getTextWidth; } });
Object.defineProperty(exports, "BASE_SIZE", { enumerable: true, get: function () { return getTextDimensions_1.BASE_SIZE; } });
Object.defineProperty(exports, "INV_BASE_SIZE", { enumerable: true, get: function () { return getTextDimensions_1.INV_BASE_SIZE; } });
var Canvas_1 = require("./Canvas");
Object.defineProperty(exports, "Canvas", { enumerable: true, get: function () { return Canvas_1.Canvas; } });
var WebCanvas_1 = require("./WebCanvas");
Object.defineProperty(exports, "WebCanvas", { enumerable: true, get: function () { return WebCanvas_1.WebCanvas; } });
