"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
var TransformComponent_1 = require("./TransformComponent");
__createBinding(exports, TransformComponent_1, "TransformComponent");
var RenderableComponent_1 = require("./RenderableComponent");
__createBinding(exports, RenderableComponent_1, "RenderableComponent");
var RunOnUpdateComponent_1 = require("./RunOnUpdateComponent");
__createBinding(exports, RunOnUpdateComponent_1, "RunOnUpdateComponent");
var Camera2D_1 = require("./Camera2D");
__createBinding(exports, Camera2D_1, "Camera2D");
__createBinding(exports, Camera2D_1, "Camera2DManager");
__createBinding(exports, Camera2D_1, "Camera2DControl");
__createBinding(exports, Camera2D_1, "Camera2DControlManager");
var Transform2D_1 = require("./Transform2D");
__createBinding(exports, Transform2D_1, "Transform2D");
__createBinding(exports, Transform2D_1, "Transform2DManager");
var Camera3D_1 = require("./Camera3D");
__createBinding(exports, Camera3D_1, "Camera3D");
__createBinding(exports, Camera3D_1, "Camera3DManager");
var Transform3D_1 = require("./Transform3D");
__createBinding(exports, Transform3D_1, "Transform3D");
__createBinding(exports, Transform3D_1, "Transform3DManager");
var UI_1 = require("./UI");
__createBinding(exports, UI_1, "UIElement");
__createBinding(exports, UI_1, "UIElementManager");
__createBinding(exports, UI_1, "UIText");
var Sprite_1 = require("./Sprite");
__createBinding(exports, Sprite_1, "Sprite");
__createBinding(exports, Sprite_1, "SpriteManager");
__createBinding(exports, Sprite_1, "SpriteClip");
__createBinding(exports, Sprite_1, "SpriteSheet");
